#!/bin/bash

if [ ! -z "$DEV" ]; then
	subdir="$1"
	target=/tmp/bl/"$subdir"
	if [ -d "$target" ]; then
		ls -l "$target"
	else
		cat "$target"
	fi
else
	if [ -z "$2" ]; then
		branch=master
	else
		branch="job-$2"
	fi

	if [ -z "$1" ]; then
		ref="$branch"^{tree}
	else
		ref="$branch":"$1"
	fi

	git --git-dir ~/.bl/state/.git cat-file -p "$ref"
fi
