#!/bin/bash

set -ex

WORKSPACE="acme-corp"

setup_base() {
	bl --workspace "$WORKSPACE" line rm acme-clothing-staging || true
	bl --workspace "$WORKSPACE" line create acme-clothing-staging -f ./acme-clothing.pipeline -d "Base Developer Pipeline for ACME"
	OVERRIDES=()
	. .overrides.acme-clothing-base.secret
	bl --workspace "$WORKSPACE" line run -d acme-clothing-staging -o name=acme-clothing-staging "${OVERRIDES[@]}" || true
}

setup_shtest() {
	bl --workspace "$WORKSPACE" line ls | tr -s ' ' | cut -d' ' -f2 | sed -E -n '2,$s/^(shtest.*)$/bl line rm \1/p' | sh -x
}

setup_base
setup_shtest
