#!/bin/bash

set -ex

setup_base() {
	bl line rm acme-clothing-base || true
	bl line create acme-clothing-base -f ./acme-clothing.pipeline -d "Base Developer Pipeline for ACME"
	OVERRIDES=()
	. .overrides.acme-clothing-base.secret
	bl line run acme-clothing-base "${OVERRIDES[@]}"
}

setup_shtest() {
	bl line ls | tr -s ' ' | cut -d' ' -f2 | sed -E -n '2,$s/^(shtest.*)$/bl line rm \1/p' | sh -x
}

setup_staging() {
	bl line ls | tr -s ' ' | cut -d' ' -f2 | sed -E -n '2,$s/^(acme-clothing-staging)$/bl line rm \1/p' | sh -x

	cat <<EOF
	Please manually create the staging pipeline, then press enter.

	1. Navigate to web dashboard
	2. Click "create pipeline"
	3. Name: "acme-clothing-staging"
	4. Clone pipeline: acme-clothing-base
	5. Click create

EOF
	read _
	bl line run -d acme-clothing-staging -o name=acme-clothing-staging
}

setup_base
setup_shtest
setup_staging
